# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/peter/Online_Assignment_In_Instant_Delivery

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/peter/Online_Assignment_In_Instant_Delivery

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/peter/Online_Assignment_In_Instant_Delivery/CMakeFiles /home/peter/Online_Assignment_In_Instant_Delivery/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/peter/Online_Assignment_In_Instant_Delivery/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named onlineAssignment

# Build rule for target.
onlineAssignment: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 onlineAssignment
.PHONY : onlineAssignment

# fast build rule for target.
onlineAssignment/fast:
	$(MAKE) -f CMakeFiles/onlineAssignment.dir/build.make CMakeFiles/onlineAssignment.dir/build
.PHONY : onlineAssignment/fast

src/Data.o: src/Data.cpp.o

.PHONY : src/Data.o

# target to build an object file
src/Data.cpp.o:
	$(MAKE) -f CMakeFiles/onlineAssignment.dir/build.make CMakeFiles/onlineAssignment.dir/src/Data.cpp.o
.PHONY : src/Data.cpp.o

src/Data.i: src/Data.cpp.i

.PHONY : src/Data.i

# target to preprocess a source file
src/Data.cpp.i:
	$(MAKE) -f CMakeFiles/onlineAssignment.dir/build.make CMakeFiles/onlineAssignment.dir/src/Data.cpp.i
.PHONY : src/Data.cpp.i

src/Data.s: src/Data.cpp.s

.PHONY : src/Data.s

# target to generate assembly for a file
src/Data.cpp.s:
	$(MAKE) -f CMakeFiles/onlineAssignment.dir/build.make CMakeFiles/onlineAssignment.dir/src/Data.cpp.s
.PHONY : src/Data.cpp.s

src/Environment.o: src/Environment.cpp.o

.PHONY : src/Environment.o

# target to build an object file
src/Environment.cpp.o:
	$(MAKE) -f CMakeFiles/onlineAssignment.dir/build.make CMakeFiles/onlineAssignment.dir/src/Environment.cpp.o
.PHONY : src/Environment.cpp.o

src/Environment.i: src/Environment.cpp.i

.PHONY : src/Environment.i

# target to preprocess a source file
src/Environment.cpp.i:
	$(MAKE) -f CMakeFiles/onlineAssignment.dir/build.make CMakeFiles/onlineAssignment.dir/src/Environment.cpp.i
.PHONY : src/Environment.cpp.i

src/Environment.s: src/Environment.cpp.s

.PHONY : src/Environment.s

# target to generate assembly for a file
src/Environment.cpp.s:
	$(MAKE) -f CMakeFiles/onlineAssignment.dir/build.make CMakeFiles/onlineAssignment.dir/src/Environment.cpp.s
.PHONY : src/Environment.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/onlineAssignment.dir/build.make CMakeFiles/onlineAssignment.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/onlineAssignment.dir/build.make CMakeFiles/onlineAssignment.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/onlineAssignment.dir/build.make CMakeFiles/onlineAssignment.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... onlineAssignment"
	@echo "... src/Data.o"
	@echo "... src/Data.i"
	@echo "... src/Data.s"
	@echo "... src/Environment.o"
	@echo "... src/Environment.i"
	@echo "... src/Environment.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

